### ISSUE TITLE
Manage Person JSON loading more efficiently

### ISSUE THREAD

**Issue by durfeeUT** [eklogi/idb#18]
Currently, both display panels retrieve the same json file separately when rendering the person.html page, which is obviously inefficient. Find a way to load it once and share it with both classes, or redesign the classes.

**Comment by iancaffey** [comment]
For Phase 1, I believe all templating is to be done server side. So you may not even have to worry about this. We can move this into a jinja template.

**Comment by iancaffey** [comment]
It's been mentioned by a TA we can setup our API for returning the 3 model instances as JSON and use React for handling everything. So we can avoid essentially all server side templating.
