### ISSUE TITLE
Setup Test/Prod Databases

### ISSUE THREAD

**Issue by iancaffey** [eklogi/idb#83]
Setup database for both test and production.

**Comment by ascensionra** [comment]
Database server is already installed configured. I will begin working on converting the models to tables.

**Comment by ascensionra** [comment]
Membership, committee, and bridge tables for these two main tables are setup. I've just populated the Membership table with data for the 115th Congress. I'll be updating the Roles table next.

**Comment by ascensionra** [comment]
Need to clean up populatedb.py to eliminate the ambiguity of some similarly-named functions. Also need to adjust workflow so it is standard throughout the module with segmenting JSON response and inserting data to the database.
